## 예제 5-3-1  다차원 배열에 데이터의 행과 열 추가하기 

In [1]:
import numpy as np                  ## 다차원 배열 모듈을 사용한다. 

In [3]:
A = np.arange(1,10).reshape(3,3)      ## 3행 3열의 2차원 배열을 만든다. 

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b = np.arange(11,14).reshape(1,3)          ## 1행 3열의 2차원 배열을 만든다. 

In [15]:
b

array([[11, 12, 13]])

In [16]:
np.append(A,b, axis=0)                 ## append 함수를 사용해서 수직축으로 하나의 행렬을 추가한다. 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [18]:
np.append(A,b.T, axis=1)                ## append 함수를 사용해서 수평축으로 하나의 행렬을 추가한다.
                                        ## 이때 열벡터로 변형하기 위해 b를 전치행렬로 바꿨다. 

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

## 예제 5-3-2  데이터프레임에 데이터의 행과 열 추가하기 

In [2]:
import pandas as pd                           ## 판다스 모듈을 사용한다. 

In [22]:
df1 = pd.DataFrame([[1, 2], [3, 4]], columns=list('가나'))      ##  2개의 원소를 가진 리스트를 리스트 내에 정의한다.
                                                                ## 열의 이름을 한글로 지정한 후에 데이터프레임 객체를 만든다.

In [40]:
df1                                                        ## 한글로 열의 레이블로 붙여있는 데이터프레임을 확인한다. 

가  나
0  1  2
1  3  4

In [23]:
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('가나'))        ## 동일한 열의 이름을 가진 데이터프레임을 만든다 

In [41]:
df2

가  나
0  5  6
1  7  8

In [24]:
df1.append(df2)                   ## append 메소드로 두 개의 데이터프레임을 수직축으로 연결한다.
                                  ##  행의 레이블은 원본과 동일하다.

가  나
0  1  2
1  3  4
0  5  6
1  7  8

In [25]:
df1.append(df2, ignore_index=True)          ## 두 개의 데이터프레임을 연결할 때 행의 레이블을 다시 지정하려면
                                            ## 매개변수 ignore_index=True 지정한다. 

가  나
0  1  2
1  3  4
2  5  6
3  7  8

In [28]:
df3 = pd.DataFrame([[9,10]], columns=list('가나'))         ## 하나의 행을 가진 데이터프레임을 만든다. 

In [29]:
df3

가   나
0  9  10

In [30]:
df1.append(df3, ignore_index=True)              ## 두 개의 데이터프레임을 수직축으로 연결한다. 

가   나
0  1   2
1  3   4
2  9  10

In [31]:
df4 = pd.DataFrame([[11],[12]], columns=list('다'))       ## 새로운 하나의 열을 가진 데이터프레임을 만든다. 

In [36]:
df4

다
0  11
1  12

In [39]:
pd.concat([df1,df4], sort=True,axis=1)          ## concat 함수로 두 개의 데이터프레임을 수형축으로 연결한다. 

가  나   다
0  1  2  11
1  3  4  12