## 예제 9-3-1 텐서와 다차원 배열 확인하기

In [1]:
import numpy as np                   ##  다차원 배열을 만드는 넘파이 모듈을 사용한다

In [2]:
a = np.random.randn(3,3,3)                   ## 3차원 형상을 가지는 다차원 배열을 만든다. 

In [3]:
a.ndim, a.shape, a.dtype                     ## 차원, 형상, 자료형을 속성으로 조회한다. 

(3, (3, 3, 3), dtype('float64'))

In [4]:
a[0]                                              ## 3차원 행렬의 첫번째 원소는 2차원 배열이다. 

array([[-0.3150773 ,  0.316396  ,  0.88055137],
       [-1.20889598,  0.98288513, -1.57711652],
       [-1.83989152,  0.24356761, -0.74681728]])

In [5]:
a[0][0]                                         ## 첫번째 원소인 행렬을 조회하고 그 내부의 첫번째 원소를 조회한다. 

array([-0.3150773 ,  0.316396  ,  0.88055137])

In [6]:
a[0,0]                                          ## 위의 방식을 숫자를 연속해서 조회할 수 있다. 

array([-0.3150773 ,  0.316396  ,  0.88055137])

In [7]:
a[0][0][0]                                     ## 색인연산자를 사용해서 가장 내부의 원소를 조회한다. 

-0.3150773038154812

In [8]:
a[0,0,0]                                     ## 정수 인덱스를 쉼표로 구분해서 제일 내부의 원소를 조회한다. 

-0.3150773038154812

In [9]:
b = np.random.rand(3,3,3,3)                 ## 4차원 배열을  하나 만든다. 

In [10]:
b.ndim, b.shape                            ##  차원과 형상을 속성으로 확인한다. 

(4, (3, 3, 3, 3))

In [11]:
b.strides                               ## 4 차원 배열은 3차원 배열로 구성한다.
                                        ## 배열을 확장할 때 3차원 요소의 바이트에 대한 정보를 관리한다.
                                        

(216, 72, 24, 8)

In [12]:
b.itemsize                              ## 하나의 원소는 8 바이트로 구성한다

8

In [13]:
b.itemsize *3                            ## 1차원 배열은 3개의 원소를 가지므로 24바이트이다 

24

In [14]:
b.itemsize *3 *3                        ## 2차원 배열은 9개의 원소를 가지므로 72바이트이다

72

In [15]:
b.itemsize *3 *3 *3                     ## 3차원 배열은  27 개의 원소를 가지므로 216 바이트이다

216