## 예제 9-1-1 벡터 알아보기

In [1]:
import numpy as np       ## 다차원 배열 모듈을 사용한다. 

In [2]:
a = np.arange(10)              ## 10개의 원소를 가지는 1차원 배열을 만든다. 

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.arange(9)                  ## 9 개의 원소를 가지는 1차원 배열을 만든다. 

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
try :
    a + b                             ## 두 차원 배열의 덧셈은 원소 별로 계산하므로 동일한 원소를 가져야 한다 
except Exception as e :
    print(e)

operands could not be broadcast together with shapes (10,) (9,) 


In [9]:
b = np.append(b,9)                     ## 두번째 배열에 원소를 하나 추가한다. 

In [10]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
c = a + b                                   ## 두 배열의 원소가 동일해서 덧셈연산이 수행된다.

In [13]:
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
d = a * 5                                  ## 하나의 배열과 상수를 곱셈연산을 한다,  
                                           ## 상수를 원소별로 처리를 하기 위해서는 동일한 배열로 만든 후에 곱셈을 수행한다.

In [17]:
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
f = np.array([5,5,5,5,5,5,5,5,5,5])              ## 동일한 상수를 가지는 배열로 변환한다 

In [19]:
a * f                                                ## 두 배열간의 원소 별로 곱셈을 수행한다. 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
aa = np.array(0)                           ## 스칼라 값을 배열로 만들어봅니다. 

In [24]:
aa

array(0)

In [25]:
type(aa)                                  ## 스칼라 값을 넣고 배열을 만들어도 다차원 배열입니다. 

numpy.ndarray

In [26]:
aa == a[0]                               ## 스칼라 값은 일반 정수 값과 동일하다. 

True