In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

## 예제 5-1-1  팬시 검색 알아보기

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])    ## 3개의 원소를 가진 리스트를 3개 리스트 내에 넣어서 다차원 배열 객체를 만든다. 

In [4]:
a                             ##  3행 3열의 다차원 배열이다. 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a[0]                          ## 정수 0으로 조회하면 첫번째 행의 1차원 배열을 조회한다. 

array([1, 2, 3])

In [6]:
a[[0]]                         ##  리스트를 색인연산에 사용할 수 있다.
                               ## 하나의 원소 0을 가진 리스트로 조회하면 2차원 배열의 형상을 유지한 1행 3열의 2차원 배열이다.

array([[1, 2, 3]])

In [7]:
a[0,2]                      ## 행과 열을 정수로 넣어 조회하면 하나의 원소의 값을 조회한다. 

3

In [8]:
a[[0,2]]                   ## 두 개의 정수가 들어있는 리스트로 조회하면 0번행과 2번행을 가진 2차원 배열이 조회된다.

array([[1, 2, 3],
       [7, 8, 9]])

In [9]:
try :
    a[[3]]                       ## 없는 인덱스 정보를 리스트에 넣어서 조회하면 예외가 발생한다. 
except Exception as e :
    print(e)

index 3 is out of bounds for axis 0 with size 3


In [10]:
b = a[[0,2]]                     ## 리스트를 넣고 조회한 후에 변수에 할당한다. 

In [11]:
b

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
b[:, [0,2]]                       ## 이 배열의 모든 행은 슬라이스로 처리하고 열은 리스트로 처리하면
                                  ## 2행 2열의 2차원 배열이 만들어진다. 

array([[1, 3],
       [7, 9]])

In [13]:
a[[0,2],[0,2]]                    ## 행과 열에 리스트를 제공하면 두 개의 리스트의 순서쌍을 만든 값을 조회한다.

array([1, 9])

In [14]:
a[np.ix_([0,2], [0,2])]            ##  이를 첫번재와 마지막행과 첫번재 열과 마지막 열로 검색을 할 때는 ix 함수를 사용한다. 

array([[1, 3],
       [7, 9]])

In [15]:
c = a[np.ix_([0,2], [0,2])]         ## 팬시 검색을 수행하면 새로운 객체를 만든다. 

In [16]:
np.may_share_memory(c,a)            ## 팬시검색은 원본과 다른 새로운 사본을 만들기 때문에 메모리를 공유하지 않는다.

False

## 예제 5-1-2  논리 검색 알아보기

In [17]:
a                                          ## 위에서 만든 배열을 조회한다. 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a > 5                                      ## 상수와 배열을 비교하면 형상이 같고 원소의 값이 논리값으로 변경된다. 

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [19]:
a[a > 5]                              ## 이를 배열의 색인연산에 넣어서 사용하면 True인 결과만 추출한다. 

array([6, 7, 8, 9])

In [20]:
(a>5) & (a< 8)                        ## 두 개의 비교를 연결해서 사용한 결과도 논리값이 배열을 만든다. 

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [21]:
a[ (a>5) & (a< 8)]                      ## 이를 색인연산에 넣어서 참인 결과만 추출한다. 

array([6, 7])

In [22]:
d = a[ (a>5) & (a< 8)]                  ## 위의 결과를 변수에 할당한다. 

In [23]:
np.may_share_memory(d,a)                ## 원본 배열과 메모리 공유하는지를 확인하면 안하는 것을 알 수 있다. 

False

In [24]:
try :
    a[ (a>5) and (a< 8)]                ## 색인연산 내에는 and, or, not을 사용할 수 없다. 대신 기호로 사용해야한다. 
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
