## 예제 9-2-1 행렬 알아보기

In [3]:
import numpy as np                       ## 다차원 배열 모듈을 사용합니다. 

In [2]:
a = np.arange(10).reshape(2,5)          ## 10개의 원소를 가진 1차원 배열을 만든 후에 2행 5열의 행렬로 변환합니다. 

In [3]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a.ndim,a.shape

(2, (2, 5))

In [5]:
a.T                                      ## 행렬의 행과 열을 변경해서 조회한다. 이를 전치행렬이라 부른다. 
                                         ## 내부의 원소의 값은 변경되지 않고 축만 변경해서 보여준다

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [6]:
t = np.transpose(a)                         ## 함수를 사용해서 다차원 배열의 축을 변경할 수 있다 

In [7]:
t == a.T

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [8]:
b = np.arange(10).reshape(5,2)             ## 또 다른 2차원 배열을 하나 더 만든다. 

In [9]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
try :
    a + b                  ## 두 배열을 더하면 형상이 달라서 계산을 하지 못한다. 
except Exception as e :
    print(e)

operands could not be broadcast together with shapes (2,5) (5,2) 


In [11]:
b = np.reshape(b,(2,5))             ## 두번째 행렬의 형상을 첫번째 행렬과 동일하게 변경한다. 

In [12]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
c = a + b                            ## 동일한 형상에 가져야 원소별로 계산이 가능하다 

In [14]:
c

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [15]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
d = a * 5                             ## 2차원 배열에 상수의 곱도 동일한 상수를 원소로 가진 2차원 배열과의 원소별 곱셈을 처리한다. 

In [18]:
d

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [19]:
f = np.array([5,5,5,5,5,5,5,5,5,5]).reshape(2,5)

In [20]:
a * f

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

## 예제 9-2-2 행렬 종류를  알아보기

In [21]:
e = np.eye(3)                              ## 대각선의 원소가 1이고 나머지는 0인 단위행렬을 만든다 

In [22]:
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
ide = np.identity(4)                     ## 대각선의 원소가 1이고 나머지는 0인 단위행렬을 만든다 

In [24]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
tri = np.tri(3)              ## 대각선과 그 밑의 원소가 1인 삼각행렬을 만든다. 

In [26]:
tri

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [27]:
tri = np.tri(3,k=1)               ## k 매개변수에 양수로 지정하면 대각선 범위 위의 원소도 1이 들어간다. 

In [28]:
tri

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
tril = np.tril([[1,2,3],[4,5,6],[7,8,9]])         ## 하삼각 행렬을 만들면 대각선과 그 밑의 인덱스 정보에만 원소의 값이 들어간다. 

In [30]:
tril

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [31]:
tril_1 = np.tril([[1,2,3],[4,5,6],[7,8,9]],-1)       ## 하삼각 행렬도 k 매개변수에 -1을 주면 대각선보다 더 밑에 원소를 세팅한다 

In [32]:
tril_1

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [33]:
tru = np.triu([[1,2,3],[4,5,6],[7,8,9]])    ## 상삼각 행렬을 만든다. 

In [34]:
tru

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [35]:
tru_1 = np.triu([[1,2,3],[4,5,6],[7,8,9]],1)   ## 상삼각 행렬도 대각선의 위치를 변경할 수 있다. 이때 양수를 사용한다

In [36]:
tru_1

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

## 예제 9-2-3 LU 분해 이해하기

In [1]:
import scipy.linalg as LA                   ## 선형대수 모듈을 사용한다. 

In [4]:
A = np.array([ [7, 3, -1, 2],                    ## 4행 4열의 다차원 배열을 만든다
               [3, 8, 1, -4], 
               [-1, 1, 4, -1], 
               [2, -4, -1, 6] ])

In [54]:
A

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])

In [43]:
P, L, U = LA.lu(A)                     ## LU 분해를 통해 하삼각행렬과 상삼각행렬로 분해한다.

In [44]:
P                                          ## 첫번째 행렬은 단위행렬이다 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
L                                          ## 두번째 행렬은 하삼각행렬이다. 

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])

In [46]:
U                                                              ## 세번째 행렬은 상삼각행렬이다.

array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])

In [50]:
A_ = np.matmul(L,U)               ## 분해된 값을 다시 행렬곱한다. 

In [53]:
np.allclose(A_ , A)                ## 분해된 결과를 합산한 것과 원본이 동일한지를 확인한다. 

True