## 예제 8-1-1  집합 알아보기 

In [1]:
import numpy as np               ## 넘파이 모듈을 사용한다

In [2]:
a = np.array([[1,2,3],[3,2,1]])      ## 2행 3열의 2차원 배열을 만든다.

In [3]:
np.unique(a)                         ## 원소듸 값들 중에 유일한 값을 조회한다. 

array([1, 2, 3])

In [4]:
np.in1d(a, 3)                               ## 배열 내에 표험된 값을 확인한다. 

array([False, False,  True,  True, False, False])

In [13]:
np.isin(a, 3)                                 ## 배열 내에 표험된 값을 확인한다. 

array([[False, False,  True],
       [ True, False, False]])

In [4]:
b = np.array([[1,2,7],[4,5,6]])             ## 2행 3열의 2차원 배열을 하나 더 만든다. . 

In [7]:
a.shape == b.shape                         ## 두 다차원 배열의 형상을 비교한다. 

True

In [6]:
np.setdiff1d(a, b)                        ## 두 다차원 배열을 사용해서 차집합을 한다. 
                                          ## 동일한 것을 빼고 a 배열 중에 있는 원소만 추출된다. 

array([3])

In [8]:
np.intersect1d(a, b)                     ## 두 다차원 배열의 교집합을 구한다. 

array([1, 2])

In [9]:
np.union1d(a, b)                             ## 두 다차원 배열의 합집합을 구한다.

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
np.setxor1d(a, b)                              ## 두 다차원 배열의 대칭 차집합을 구한다.

array([3, 4, 5, 6, 7])