## 예제 9-7-1 선형변환 알아보기

In [1]:
import numpy as np                   ## 다차원 배열의 모듈을 사용한다 

In [2]:
A = np.array([[-1,1],[1,1]])           ## 2행 2열의 배열을 만든다 

In [3]:
b = np.array([3,1])                    ## 1차원 배열을 만든다 

In [4]:
np.dot(A,b)                            ## 행렬과 벡터의 닷연산을 수행하면 하나의 벡터가 만들어진다.
                                       ##  b 벡터를 선형으로 이동한 결과를 게산한 것이다 

array([-2,  4])

## 예제 9-7-2 고유값과 고유벡터 알아보기 

In [5]:
import numpy.linalg as LA               ## 선형대수 함수를 관리하는 모듈을 사용한다. 

In [6]:
A = np.array([[3,0],[8,-1]])             ## 2행 2열의 2차원 배열을 만든다

In [7]:
x = np.array([1,2])                      ## 1차원 배열을 만든다. 

In [8]:
E = np.eye(2)                            ## 단위행렬을 만든다. 

In [26]:
E

array([[1., 0.],
       [0., 1.]])

In [9]:
LA.det(A - 3*E)                      ##  행렬에 단위행렬에 상수배를 곱하고 뺀 후에 행렬식이 0이면 상수값이 고유값이다 

0.0

In [10]:
c = np.dot(A,x)                     ## 두 배열의 닷 연산을 처리한다. 

In [11]:
c

array([3, 6])

In [12]:
3 * x                               ## 계산된 결과가 x에 상수 3을 곱한 결과와 같다. 

array([3, 6])

In [13]:
B = np.array([[1,3],[3,1]])           ## 하나의 배열을 만든다. 

In [14]:
v,w = LA.eig(B)                       ## 고유값과 고유벡타를 구한다. 

In [15]:
v                                     ## 두 개의 고유값을 구한다 

array([ 4., -2.])

In [16]:
w                                      ## 두 개의 고유벡터를 구한다 

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [17]:
E = np.eye(2)

In [18]:
E

array([[1., 0.],
       [0., 1.]])

In [19]:
LA.det(B - (4 * E))                    ## 고유값을 행렬식으로 구하는 산식을 사용하면 0이되어 이 값이 고유값이다 

0.0

In [20]:
x = np.array([ 0.70710678, -0.70710678])   ## 벡터를 하나 만들고 

In [21]:
np.dot(B,x)                                  ## 행렬과 벡터를 닷연산을 해서 벡터를 구한다. 

array([-1.41421356,  1.41421356])

In [22]:
-2*x                                        ## 고유값과 벡터를 곱하면 같은 벡터를 만든다 

array([-1.41421356,  1.41421356])

In [23]:
y = np.array([ 0.70710678,  0.70710678])

In [24]:
np.dot(B,y)

array([2.82842712, 2.82842712])

In [25]:
4*y

array([2.82842712, 2.82842712])