In [1]:
import numpy as np

## 예제 7-1-1 수학 메소드 알아보기

In [2]:
y = np.linspace(1,10,10)            ## 1부 10까지의 숫자중에 10개의 원소를 만든다 

In [3]:
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
y + y                                                 ## 동일한 배열을 덧셈연산자로 더한다

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [5]:
y.__add__(y)                                                  ## 덧셈연산자는 스페셜메소드를 사용한 계산이다 

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [6]:
np.add(y,y)                                                     ## 추가적으로 덧셈 함수도 추가도 제공한다. 

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [7]:
y.sum()                                          ## 모든 원소의 합을 sum 메소드로 구한다

55.0

In [8]:
z = y.cumsum()                                 ## 누적에 대한 합은 cumsum 메소드로 확인한다 

In [9]:
z

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

In [10]:
y.prod()                                    ## 원소들의 곱을 확인한다 

3628800.0

In [11]:
w = y.cumprod()                         ## 각 원소들이 누적된 곱을 확인한다 

In [12]:
w

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])