## 예제 9-5-4 outer 함수 처리  알아보기

In [1]:
import numpy as np                ##  다차원 배열의 모듈을 사용한다. 

In [3]:
a = np.array([1,2,3])         ## 1차원 배열을 만든다

In [4]:
b = np.array([5,6,7])

In [5]:
np.outer(a,b)                               ## outer 함수로 두 벡터를 구한다. 
                                            ##  계산결과를 보면 열벡터와 행벡터의 곱셈으로 구해진 것을 알 수 있다, 

array([[ 5,  6,  7],
       [10, 12, 14],
       [15, 18, 21]])

In [13]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])      ## 두 개의 2차원 배열을 만든다 
y = np.array([[7, 8, 9], [4,5,6], [1,2,3]])

In [8]:
np.outer(x,y)                                        ## 두 개의 2차원 배열의 outer 함수의 결과는 9행 9열이 된다. 

array([[ 7,  8,  9,  4,  5,  6,  1,  2,  3],
       [14, 16, 18,  8, 10, 12,  2,  4,  6],
       [21, 24, 27, 12, 15, 18,  3,  6,  9],
       [28, 32, 36, 16, 20, 24,  4,  8, 12],
       [35, 40, 45, 20, 25, 30,  5, 10, 15],
       [42, 48, 54, 24, 30, 36,  6, 12, 18],
       [49, 56, 63, 28, 35, 42,  7, 14, 21],
       [56, 64, 72, 32, 40, 48,  8, 16, 24],
       [63, 72, 81, 36, 45, 54,  9, 18, 27]])

In [14]:
x = np.reshape(x,(9,1))                    ## 열벡터로 변환한다. 

In [15]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
y = np.reshape(y,(1,9))                              ## 행벡터로 변환한다. 

In [18]:
y

array([[7, 8, 9, 4, 5, 6, 1, 2, 3]])

In [17]:
np.dot(x,y)                                         ## 행렬곱으로 계산을 하면 outer와 동일한 결과가 나온다

array([[ 7,  8,  9,  4,  5,  6,  1,  2,  3],
       [14, 16, 18,  8, 10, 12,  2,  4,  6],
       [21, 24, 27, 12, 15, 18,  3,  6,  9],
       [28, 32, 36, 16, 20, 24,  4,  8, 12],
       [35, 40, 45, 20, 25, 30,  5, 10, 15],
       [42, 48, 54, 24, 30, 36,  6, 12, 18],
       [49, 56, 63, 28, 35, 42,  7, 14, 21],
       [56, 64, 72, 32, 40, 48,  8, 16, 24],
       [63, 72, 81, 36, 45, 54,  9, 18, 27]])