In [5]:
import numpy as np

## 예제 7-3-1 다차원 배열의 축에 따른 원소계산 방식 

In [3]:
a = np.arange(1,11).reshape(2,5)           ## 1차원 배열을 만들고 형상을 바꿔서 2차원 배열로 변경한다. 

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
np.sum(a,axis=0)                           ## 배열의 축을 기준으로 합산을 한다.
                                           ## 0번축은 열의 합산을 구한다 

array([ 7,  9, 11, 13, 15])

In [6]:
np.sum(a,axis=1)                         ## 1번축은 지정해서 행의 합산을 구한다. 

array([15, 40])

In [8]:
np.max(a, axis=0)                       ## 열의 최대값을 구한다.

array([ 6,  7,  8,  9, 10])

In [9]:
np.max(a, axis=1)                      ## 행의 최대값을 구한다. 

array([ 5, 10])

## 예제 7-3-2 시리즈와 데이터프레임이 레이블에 따른 원소 계산방식

In [3]:
import pandas as pd                                  ## 판다스 모듈을 사용한다. 

In [9]:
df = pd.DataFrame(np.arange(9.).reshape((3, 3)),              ## 데이터프레임 객체를 만들기 위해 3행 3열의 데이터를 지정한다. 
                columns=list('bcd'),                          ## 열의 레이블을 부여한다
                index=['제주도', '서울시', '경기도'])         ## 행의 레이블을 부여한다. 


In [10]:
df

b    c    d
제주도  0.0  1.0  2.0
서울시  3.0  4.0  5.0
경기도  6.0  7.0  8.0

In [11]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),             
                columns=list('acd'),                      ## 열의 레이블을 부여한다
                index=['충청남도', '서울시', '경기도'])   ## 행의 레이블을 부여한다

In [12]:
df1

a    c    d
충청남도  0.0  1.0  2.0
서울시   3.0  4.0  5.0
경기도   6.0  7.0  8.0

In [14]:
df + df1                                  ## 두 데이터프레임을 합산한다.
                                          ## 행과 열의 동일한 레이블이 있는 경우에만 합산을 한다.
                                          ## 새로운 행과 열의 레이블을 가진 데이터프레임이 만들어진다.
                                          ## 일치하지 않는 것은 NaN으로 들어간다. 

a   b     c     d
경기도  NaN NaN  14.0  16.0
서울시  NaN NaN   8.0  10.0
제주도  NaN NaN   NaN   NaN
충청남도 NaN NaN   NaN   NaN

In [17]:
df.add(df1)                              ## add 메소드를 사용해서 계산한 경우도 동일하다 

a   b     c     d
경기도  NaN NaN  14.0  16.0
서울시  NaN NaN   8.0  10.0
제주도  NaN NaN   NaN   NaN
충청남도 NaN NaN   NaN   NaN

In [27]:
df.add(df1, axis='index')              ## 인덱스 레이블을 기준으로 합산을 해도 결과는 동일하다 

a   b     c     d
경기도  NaN NaN  14.0  16.0
서울시  NaN NaN   8.0  10.0
제주도  NaN NaN   NaN   NaN
충청남도 NaN NaN   NaN   NaN

In [22]:
df.add(df1, fill_value=0)             ## 결측값 대신에 해당값을 지정한 경우는 두 데이터프레임중에 한 곳이 있으면 계산을 한다.
                                      ## 두 곳이 불일치하는 곳은 NaN으로 처리된다. 

a    b     c     d
경기도   6.0  6.0  14.0  16.0
서울시   3.0  3.0   8.0  10.0
제주도   NaN  0.0   1.0   2.0
충청남도  0.0  NaN   1.0   2.0