In [2]:
!python --version

Python 3.7.4


## 예제 3-3-1  다차원 배열 알아보기

In [3]:
import numpy as np           ## 다차원 배열의 모듈을 import 한다. 모듈의 별칭은 np를 사용한다.

In [4]:
np.__version__

'1.17.2'

In [3]:
a = np.array([1,2,3,4])           ## array 함수에 4개의 원소를 가진 리스트를 전달해서 다차원 배열을 하나 만든다.

In [4]:
a                                            ## 다차원 배열을 확인할 수 있다.

array([1, 2, 3, 4])

In [5]:
print(a)                                  ## print 함수로 출력할 때는 리스트와 구분하기 위해 원소들 사이에 쉼표가 없이 출력된다.

[1 2 3 4]


In [6]:
import collections.abc as abc                  ## 추상 클래스와 관계를 알아보기위해 모듈을 import 한다

In [7]:
issubclass(type(a), abc.MutableSequence)      ## 변경이 가능한  MutableSequence 클래스를 상속하지 않는 것을 알 수 있다.

False

In [8]:
abc.MutableSequence.__abstractmethods__         ## 반드시 구현되어야 할 메소드를 확인한다.

frozenset({'__delitem__', '__getitem__', '__len__', '__setitem__', 'insert'})

In [9]:
dir(np.ndarray).count('insert')                ## 다차원 배열은 insert 메소드를 구현하지 않았다.

0

In [10]:
a.dtype                 ## 다차원 배열의 모든 원소는 하나의 자료형으로 구성되어야 한다. dtype 속성에 하나의 자료형을 관리한다.

dtype('int64')

In [9]:
a.ndim, a.shape, a.itemsize,           ## 다차원 배열은 차원, 형상, 하나의 원소의 바이트크기를 속성으로 관리한다

(1, (4,), 8)

In [10]:
a.strides                        ##  확장할 때 총 사이즈를 확인하는 속성인 strides도 있다. 1차원이므로 원소의 크기만 가지고 있다.

(8,)

In [11]:
a.data                              ## 다차원 배열을 만들면 데이터는 메모리에 로딩된다. 이 메모리를 관리하는 속성이 data이다

In [12]:
a.data.obj                        ## data내의 obj 속성을 사용해서 저장된 값을 확인할 수 있다.

array([1, 2, 3, 4])

In [13]:
a.tolist()                   ## 리스트 객체로 변환은 tolist 메소드로 한다

[1, 2, 3, 4]

In [16]:
c = np.array([1,2,3])                        ## 다른 다차원 배열을 하나 만든다.

In [17]:
d = np.asarray(c)                           ## asarray 함수에 다차원 배열을 넣고 새로운 다차원 배열을 만들어서 변수에 할당한다.

In [18]:
c is d                                           ## 두 개의 다차원 배열의 동일한 이유는 asarray는 다차원배열일 경우는 기존 다차원배열을 그대로 전달하기 때문이다

True

In [19]:
e = np.asarray([1,2,3])              ## 리스트를 전달해서 다차원 배열을 만들면 새로운 다차원 배열을 생성한다.

In [20]:
c is e                                        ## 두 개의 다차원 배열의 원소는 동일하지만 다른 객체이다

False

In [21]:
f = e.copy()                          ## copy 메소드로 새로운 다차원 배열을 만든다.

In [22]:
e is f

False

In [23]:
g = np.array(f)            ## array 함수에 다차원 배열을 만들면 기존 다차원 배열을 copy하는 것과 같다.

In [24]:
g is f

False