## 예제 9-6-1 행렬식과 역행렬  알아보기

In [1]:
import numpy as np                ##  다차원 배열의 모듈을 사용한다. 

In [7]:
from numpy import linalg as LA       ##  선형대수 함수를 가진 모듈을 사용한다. 

In [8]:
a = np.arange(1,5).reshape(2,2)         ## 2행 2열의 배열을 만든다. 

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
LA.det(a)                             ## 행렬식을 구한다. 

-2.0000000000000004

In [14]:
b = np.arange(11,20).reshape(3,3)            ## 3행 3열의 2차원 배열을 만든다. 

In [15]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [16]:
LA.det(b)                                    ## 행렬식을 구한다. 

-5.8972434778618435e-15

In [18]:
c = LA.inv(a)                          ##  행렬식이 0이 아닌 경우 역행렬을 구한다. 

In [19]:
c

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
d = LA.inv(b)                            ## 역행렬을 구한다. 

In [21]:
d

array([[ 5.0871225e+14, -1.0174245e+15,  5.0871225e+14],
       [-1.0174245e+15,  2.0348490e+15, -1.0174245e+15],
       [ 5.0871225e+14, -1.0174245e+15,  5.0871225e+14]])

In [19]:
np.dot(a,c)                                  ## 역행렬과의 닷연산을 하면 단위행렬이 나온다. 

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [20]:
np.dot(c,a)                              ## 아주 작은 값이 원소로 들어있다. 

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [21]:
f = np.eye(2)                              ## 하나의 단위해열을 만든다. 

In [23]:
np.allclose(np.dot(a,c),f)                 ## 단위행렬과 같은지를 비교하면 동일하다 

True

In [24]:
np.allclose(np.dot(c,a),f)

True

In [30]:
g = np.array([[1,3],[1,3]])             ## 2행 2열의 다차원 배열을 만든다. 

In [31]:
LA.det(g)                               ## 행렬식을 구한다. 0이다. 

0.0

In [33]:
try :
    LA.inv(g)                          ## 행렬식이 0인 경우는 역행렬이 없다. 
except Exception as e :
    print(e)

Singular matrix


In [34]:
LA.pinv(g)                              ## 대신 유사 역행렬을 구할 수 있다. 

array([[0.05, 0.05],
       [0.15, 0.15]])